import './globals.css'
import { Inter } from 'next/font/google'
import MyContext from '@/Helper/Context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
      <MyContext>
      {children}
      </MyContext>
      </body>
    </html>
  )
}
